services:
  postgresql:
    hostname: pgsql-15
    container_name: pgsql-15
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=database_lab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pgsql/15/data
    volumes:
      - ./.data:/pgsql/15/data
    networks:
      - pgsql_net

  pgadmin:
    hostname: pgadmin
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=database_lab@email.com
      - PGADMIN_DEFAULT_PASSWORD=je!8iz65LwrebA1@jesw
    ports:
      - 8500:80
    depends_on:
      - postgresql
    networks:
      - pgsql_net

networks:
  pgsql_net:
    name: pgsql_net
    driver: bridge