services:
  postgres:
    hostname: pgsql-14
    container_name: pgsql-14
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/pgsql/14/data
    ports:
      - 5432:5432
    volumes:
      - ./.data:/pgsql/14/data
      - ./.shared:/tmp
    networks:
      - pgsql_net

  pgadmin:
    hostname: pgadmin
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=database_lab@email.com
      - PGADMIN_DEFAULT_PASSWORD=je!8iz65LwrebA1@jesw
    ports:
      - 8500:80
    depends_on:
      - postgres
    volumes:
      - ./.pgadmin:/var/lib/pgadmin
    networks:
      - pgsql_net

networks:
  pgsql_net:
    name: pgsql_net
    driver: bridge
